Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kirigami': '@stable'
    'frameworks/syndication': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kconfig': '@stable'
