# SPDX-FileCopyrightText: 2021 Tobias Fella <tobias.fella@kde.org>
# SPDX-License-Identifier: BSD-2-Clause

Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows', 'Android']
  'require':
    'frameworks/extra-cmake-modules': 'Frameworks/6.24'
    'frameworks/kcoreaddons': 'Frameworks/6.24'
    'frameworks/kirigami': 'Frameworks/6.24'
    'frameworks/syndication': 'Frameworks/6.24'
    'frameworks/ki18n': 'Frameworks/6.24'
    'frameworks/kconfig': 'Frameworks/6.24'
    'frameworks/threadweaver': 'Frameworks/6.24'
    'frameworks/kcolorscheme': 'Frameworks/6.24'
    'frameworks/kiconthemes': 'Frameworks/6.24'
    'libraries/kirigami-addons': 'v1.11.0'
    'third-party/qtkeychain': '@latest'

- 'on': ['Linux', 'FreeBSD', 'Windows']
  'require':
    'frameworks/qqc2-desktop-style': 'Frameworks/6.24'
    'frameworks/kcrash': 'Frameworks/6.24'

- 'on': ['Linux', 'FreeBSD']
  'require':
    'frameworks/kdbusaddons': 'Frameworks/6.24'
    'frameworks/kwindowsystem': 'Frameworks/6.24'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD', 'Windows' ]
